docker push jyr20/deptmeeting-frontend-principal
echo "front-principal pusheado!"
docker push jyr20/deptmeeting-mf-home
echo "mf-home pusheado!"
docker push jyr20/deptmeeting-mf-informacion
echo "mf-informacion pusheado!"
docker push jyr20/deptmeeting-mf-kanbanplus
echo "mf-kanbanplus pusheado!"
docker push jyr20/deptmeeting-mf-login
echo "mf-login pusheado!"
docker push jyr20/deptmeeting-mf-perfil
echo "mf-perfil pusheado!"
docker push jyr20/deptmeeting-mf-proyectos
echo "mf-proyectos pusheado!"
docker push jyr20/deptmeeting-mf-tareas
echo "mf-tareas pusheado!"
